### ISSUE TITLE
compiler warning: UIWebView depreciated

### ISSUE THREAD

**Issue by sam-parsons** [sam-parsons/UltiMet-Lite#1]
use WKWebView

SettingsViewController - line 91

```
private func webViewDidFinishLoad(webView: UIWebView) {
    arrIndexProtocol?.setArrIndex(index: arrIndex)
}
```

**Comment by MiguelTepale** [comment]
Hey, did you commit "SettingsViewController"? It doesn't appear when I forked it.

**Comment by sam-parsons** [comment]
Yeah, I am pretty sure it is up there...  maybe this link?

https://github.com/sam-parsons/UltiMet-Lite/blob/master/MidiMetronome/SettingsViewController.swift

**Comment by MiguelTepale** [comment]
Got it! I'll look at this during my lunch break.

**Comment by MiguelTepale** [comment]
I'm curious, did you NOT commit the "AudioKit" pod to this repo? It doesn't appear when I forked it. If not, it's fine. I just need to know so that I don't commit it and push it to your repo.

**Comment by sam-parsons** [comment]
Yes, it was a huge folder, so you'll have to add it to your fork.

**Comment by MiguelTepale** [comment]
Good choice. I remember when we tried uploading this massive file to Github; good work around.
